config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  get "up" => "rails/health#show", as: :rails_health_check

  get "users/", to: "users#other_users", as: "users"
  get "users/:nickname", to: "users#other_user", as: "other_user"
  get ":nickname", to: "users#show", as: "profile"
  get ":nickname/edit", to: "users#edit", as: "edit_profile"
  patch ":nickname", to: "users#update", as: "update_profile"

  get ":nickname/posts/new", to: "posts#new", as: "post_new"
  get ":nickname/posts/:id/edit", to: "posts#edit", as: "post_edit"
  post ":nickname/posts", to: "posts#create", as: :create_post
  patch ":nickname/posts/:id", to: "posts#update", as: "update_post"
  put ":nickname/posts/:id", to: "posts#update"
  delete ":nickname/posts/:id", to: "posts#destroy", as: "delete_post"
  get ":nickname/posts", to: "posts#index", as: "posts"

  resources :users, only: [:show] do
    member do
      get :followers, :following
    end
  end

  resources :subscriptions, only: [:create, :destroy]

  resources :posts, only: [] do
    member do
      post 'like', to: 'likes#create'
      delete 'like', to: 'likes#destroy'
      get 'show', to: 'posts#show', as: :show
    end
    resources :comments, only: [:create, :destroy]
  end

  root "home#index"
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :post
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_post

  def create
    @comment = @post.comments.build(comment_params)
    @comment.user = current_user

    if @comment.save
      respond_to do |format|
        format.turbo_stream
      end
    else
      respond_to do |format|
        format.html { redirect_to post_path(@post), alert: 'Comment could not be created' }
        format.turbo_stream
      end
    end
  end

  def destroy
    @comment = @post.comments.find(params[:id])
    if @comment.user == current_user
      @comment.destroy
      respond_to do |format|
        format.turbo_stream
      end
    else
      respond_to do |format|
        format.html { redirect_to post_path(@post), alert: 'You can only delete your own comments' }
        format.turbo_stream
      end
    end
  end

  private

  def set_post
    @post = Post.find(params[:post_id])
  end

  def comment_params
    params.require(:comment).permit(:content)
  end
end

app/views/comments/_comment.html.erb
<div id="<%= dom_id(comment) %>" class="comment bg-gray-100 p-4 rounded-lg shadow-md">
  <% if comment.user.avatar.attached? %>
    <%= image_tag comment.user.avatar, class: 'w-10 h-10 p-1 rounded-full ring-2 ring-gray-300 dark:ring-gray-500' %>
  <% else %>
    <p>No avatar available</p>
  <% end %>

  <p class="text-sm text-gray-600 mt-5"><strong><%= comment.user.nickname %>:</strong></p>
  <p class="text-gray-800 mb-2"><%= comment.content %></p>
  <p class="text-sm text-gray-500 mb-6">Commented on: <%= comment.created_at.strftime("%B %d, %Y") %></p>

  <% if comment.user_id == current_user.id %>
    <%= link_to 'Delete', post_comment_path(comment.post, comment), method: :delete, data: { turbo_method: :delete }, class: "text-red-500 hover:text-red-700" %>
  <% end %>
</div>

app/views/comments/_form.html.erb
<%= form_with(model: [ @post, @post.comments.build ], local: false, id: "new_comment", class: "space-y-4") do |form| %>
  <div class="field">
    <%= form.label :content, class: "block text-lg font-medium text-gray-700" %>
    <%= form.text_area :content, class: "w-full mt-2 p-2 border rounded-md" %>
  </div>
  <div class="actions">
    <%= form.submit "Add Comment", class: "bg-blue-500 text-white px-4 py-2 rounded-md hover:bg-blue-600" %>
  </div>
<% end %>

app/views/comments/create.turbo_stream.erb
<%= turbo_stream.append "comments" do %>
  <%= render @comment %>
<% end %>

<%= turbo_stream.replace "new_comment" do %>
  <%= render 'comments/form', post: @post %>
<% end %>

app/views/comments/destroy.turbo_stream.erb
<%= turbo_stream.remove dom_id(@comment) %>