config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  get "up" => "rails/health#show", as: :rails_health_check

  get "users/", to: "users#other_users", as: "users"
  get "users/:nickname", to: "users#other_user", as: "other_user"
  get ":nickname", to: "users#show", as: "profile"
  get ":nickname/edit", to: "users#edit", as: "edit_profile"
  patch ":nickname", to: "users#update", as: "update_profile"

  get ":nickname/posts/new", to: "posts#new", as: "post_new"
  get ":nickname/posts/:id/edit", to: "posts#edit", as: "post_edit"
  post ":nickname/posts", to: "posts#create", as: :create_post
  patch ":nickname/posts/:id", to: "posts#update", as: "update_post"
  put ":nickname/posts/:id", to: "posts#update"
  delete ":nickname/posts/:id", to: "posts#destroy", as: "delete_post"
  get ":nickname/posts", to: "posts#index", as: "posts"

  resources :users, only: [:show] do
    member do
      get :followers, :following
    end
  end

  resources :subscriptions, only: [:create, :destroy]

  resources :posts, only: [] do
    member do
      post 'like', to: 'likes#create'
      delete 'like', to: 'likes#destroy'
      get 'show', to: 'posts#show', as: :show
    end
    resources :comments, only: [:create, :destroy]
  end

  root "home#index"
end

app/models/user.rb
class User < ApplicationRecord
  # Подписчики, которые подписаны на этого пользователя
  has_many :active_subscriptions, class_name: "Subscription", foreign_key: "follower_id", dependent: :destroy
  has_many :following, through: :active_subscriptions, source: :followed

  # Пользователи, на которых подписан этот пользователь
  has_many :passive_subscriptions, class_name: "Subscription", foreign_key: "followed_id", dependent: :destroy
  has_many :followers, through: :passive_subscriptions, source: :follower

  # Проверки полей при регистрации
  validates :name, presence: true
  validates :lastname, presence: true
  validates :nickname, presence: true, uniqueness: true, format: { with: /\A[a-zA-Z0-9_]+\z/, message: "can only contain letters, numbers, and underscores" }
  validates :age, numericality: { only_integer: true, greater_than_or_equal_to: 0 }

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  # Ассоциация для постов
  has_many :posts

  # Подключение Active Storage для аватара
  has_one_attached :avatar

  has_many :likes, dependent: :destroy
  has_many :liked_posts, through: :likes, source: :post

  def follow(other_user)
    active_subscriptions.create(followed_id: other_user.id)
  end

  def unfollow(other_user)
    active_subscriptions.find_by(followed_id: other_user.id).destroy
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  # Требуем аутентификацию для доступа к профилю
	before_action :authenticate_user!
  before_action :set_user, only: [:show, :edit, :update]

	def show
    current_nickname = params[:nickname]
    @naming_convention = User.find_by(nickname: current_nickname)

    if @naming_convention && @naming_convention.email == current_user.email
      @user = current_user # Получаем информацию о текущем пользователе
      @posts = @user.posts # Получаем все посты текущего пользователя
      @following_count = @user.following.count # Количество подписок
      @followers_count = @user.followers.count # Количество подписчиков
    else
      redirect_to profile_path(current_user.nickname)
    end
  end

  def edit
    @user = User.find_by(nickname: params[:nickname])
  end

  def update
    @user = User.find_by(nickname: params[:nickname])
    if @user.update(user_params)
      redirect_to profile_path(@user.nickname), notice: 'Profile was successfully updated.'
    else
      render :edit
    end
  end

  def other_users
    @users = User.where.not(id: current_user.id)
  end

  def other_user
    nickname = params[:nickname]
    @naming_convention = User.find_by(nickname: nickname)

    if @naming_convention
      @user = @naming_convention
      @posts = @user.posts
      @following_count = @user.following.count
      @followers_count = @user.followers.count
    else
      redirect_to users_path, alert: "User not found"
    end
  end

  private

  def set_user
    @user = User.find_by(nickname: params[:nickname])
  end

  def user_params
    params.require(:user).permit(:name, :lastname, :nickname, :age, :avatar)
  end
end

app/views/users/edit.html.erb
<section class="pt-70 w-full h-screen bg-slate-200">
	<h2 class="text-6xl	mt-6 mx-auto max-w-sm">Edit Profile</h2>

	<%= form_for @user, url: update_profile_path(@user.nickname), html: { multipart: true, class: 'max-w-sm mx-auto' } do |f| %>
		<div class="field mb-5 mt-7">
			<%= f.label :name, class: "block mb-2 text-sm font-medium text-gray-900 dark:text-white" %>
			<%= f.text_field :name, class: "bg-gray-50 border border-gray-300 text-gray-900 text-sm rounded-lg focus:ring-blue-500 focus:border-blue-500 block w-full p-2.5 dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400 dark:text-white dark:focus:ring-blue-500 dark:focus:border-blue-500" %>
		</div>

		<div class="field mb-5">
			<%= f.label :lastname, class: "block mb-2 text-sm font-medium text-gray-900 dark:text-white" %>
			<%= f.text_field :lastname, class: "bg-gray-50 border border-gray-300 text-gray-900 text-sm rounded-lg focus:ring-blue-500 focus:border-blue-500 block w-full p-2.5 dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400 dark:text-white dark:focus:ring-blue-500 dark:focus:border-blue-500" %>
		</div>

		<div class="field mb-5">
			<%= f.label :nickname, class: "block mb-2 text-sm font-medium text-gray-900 dark:text-white" %>
			<%= f.text_field :nickname, class: "bg-gray-50 border border-gray-300 text-gray-900 text-sm rounded-lg focus:ring-blue-500 focus:border-blue-500 block w-full p-2.5 dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400 dark:text-white dark:focus:ring-blue-500 dark:focus:border-blue-500" %>
		</div>

		<div class="field mb-5">
			<%= f.label :age, class: "block mb-2 text-sm font-medium text-gray-900 dark:text-white" %>
			<%= f.number_field :age, class: "bg-gray-50 border border-gray-300 text-gray-900 text-sm rounded-lg focus:ring-blue-500 focus:border-blue-500 block w-full p-2.5 dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400 dark:text-white dark:focus:ring-blue-500 dark:focus:border-blue-500" %>
		</div>

		<div class="field mb-5">
			<%= f.label "Upload file", class: "block mb-2 text-sm font-medium text-gray-900 dark:text-white" %>
			<%= f.file_field :avatar, class: "block w-full text-sm text-gray-900 border border-gray-300 rounded-lg cursor-pointer bg-gray-50 dark:text-gray-400 focus:outline-none dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400" %>
		</div>

		<div class="actions mb-5">
			<%= f.submit "Update Profile", class: "w-full text-gray-500 font-medium text-base bg-gray-100 file:cursor-pointer cursor-pointer file:border-0 file:py-2.5 file:px-4 file:mr-4 file:bg-gray-800 file:hover:bg-gray-700 file:text-white rounded" %>
		</div>
	<% end %>
	
	<div class="max-w-sm mx-auto mt-10">
		<%= link_to 'Back', profile_path(@user.nickname), class: "text-white bg-gradient-to-br from-green-400 to-blue-600 hover:bg-gradient-to-bl focus:ring-4 focus:outline-none focus:ring-green-200 dark:focus:ring-green-800 font-medium rounded-lg text-sm px-5 py-2.5 text-center me-2 mb-2" %>
	</div>
</section>

app/views/users/other_user.html.erb
<main class="profile-page bg-slate-200">
  <section class="relative py-16 bg-blueGray-200 mt-24"> <!-- Добавлен отступ сверху -->
    <div class="container mx-auto px-4">
      <div class="relative flex flex-col min-w-0 break-words bg-white w-full mb-6 shadow-xl rounded-lg">
        <div class="px-6">
          <div class="flex flex-wrap justify-center">
            <div class="w-full lg:w-3/12 px-4 lg:order-2 flex justify-center">
              <div class="relative w-40 h-40">
                <% if @user.avatar.attached? %>
                  <%= image_tag @user.avatar, class: 'shadow-xl rounded-full h-full w-full align-middle border-none' %> <!-- Обновлены стили -->
                <% else %>
                  <p>No avatar available</p>
                <% end %>
              </div>
            </div>
            <div class="w-full lg:w-4/12 px-4 lg:order-3 lg:text-right lg:self-center">
              <div class="py-6 px-3 mt-32 sm:mt-0">
                <div>
                  <p class="text-xl font-bold"><%= @user.name %> <%= @user.lastname %></p>
                  <p class="text-lg text-gray-600">Age: <%= @user.age %></p>
                </div>
                <% if not(@user == current_user) %>
                  <% if current_user.following.include?(@user) %>
                    <%= button_to 'Unfollow', subscription_path(current_user.active_subscriptions.find_by(followed_id: @user.id)),
                      method: :delete,
                      class: "text-white bg-gradient-to-br from-green-400 to-blue-600 hover:bg-gradient-to-bl focus:ring-4 focus:outline-none focus:ring-green-200 dark:focus:ring-green-800 font-medium rounded-lg text-sm px-5 py-2.5 text-center me-2 mb-2" 
                    %>
                  <% else %>
                    <%= button_to 'Follow', subscriptions_path(followed_id: @user.id),
                      class: "text-white bg-gradient-to-br from-pink-500 to-orange-400 hover:bg-gradient-to-bl focus:ring-4 focus:outline-none focus:ring-pink-200 dark:focus:ring-pink-800 font-medium rounded-lg text-sm px-5 py-2.5 text-center me-2 mb-2"
                    %>
                  <% end %>
                <% end %>
              </div>
            </div>
            <div class="w-full lg:w-4/12 px-4 lg:order-1">
              <div class="flex justify-center py-4 lg:pt-4 pt-8">
                <div class="mr-4 p-3 text-center">
                  <span class="text-xl font-bold block uppercase tracking-wide text-blueGray-600">
                    <%= @following_count %>
                  </span>
                  <span class="text-sm text-blueGray-400">
                    Following
                  </span>
                </div>
                <div class="mr-4 p-3 text-center">
                  <span class="text-xl font-bold block uppercase tracking-wide text-blueGray-600">
                    <%= @followers_count %>
                  </span>
                  <span class="text-sm text-blueGray-400">
                    Followers
                  </span>
                </div>
                <div class="lg:mr-4 p-3 text-center">
                  <span class="text-xl font-bold block uppercase tracking-wide text-blueGray-600">
                    <%= @posts.count %>
                  </span>
                  <span class="text-sm text-blueGray-400">
                    Posts
                  </span>
                </div>
              </div>
            </div>
          </div>
          <div class="text-center mt-12">
            <h3 class="text-4xl font-semibold leading-normal mb-2 text-blueGray-700 mb-2">
              <%= @user.nickname %>
            </h3>
          </div>
        </div>
      </div>
    </div>
  </section>

  <!-- Блок для вывода постов пользователя -->
  <section class="py-8">
    <div class="container mx-auto px-4">
      <div class="flex flex-wrap justify-center">
        <% @posts.each do |post| %>
          <div class="w-full md:w-1/2 lg:w-1/3 xl:w-1/4 px-4 mb-8">
            <div class="bg-white shadow-lg rounded-lg p-4">
              <%= link_to show_post_path(post.id), class: "text-xl font-semibold text-gray-800 mb-2" do %>
                <%= post.title %>
              <% end %>
              <p class="text-sm text-gray-600"><%= post.description %></p>

              <% if post.image.attached? %>
                <%= image_tag post.image, class: "mt-4 rounded-lg" %>
              <% end %>

              <div class="flex justify-between items-center mt-4">
                <%= render 'likes/like', post: post %>

                <span><%= post.comments.count %> Comments</span>

                <% if post.user_id == current_user.id %>
                  <div class="flex space-x-4">
                    <%= link_to "Edit", post_edit_path(current_user.nickname, post.id),
                      class: "text-blue-500"
                    %>
                    <%= link_to "Delete", delete_post_path(current_user.nickname, post.id), data: { turbo_method: :delete, turbo_confirm: "Are you sure?" } %>
                  </div>
                <% end %>
              </div>
            </div>
          </div>
        <% end %>
      </div>
    </div>
  </section>
</main>

app/views/users/other_users.html.erb
<section class="pt-70 w-full h-screen bg-slate-200">

  <div class="w-[1000px] mx-auto">
    <h1 class="text-5xl mt-6">Users</h1>
  </div>
  
  <div class="w-full max-w-5xl mx-auto grid grid-cols-1 sm:grid-cols-2 md:grid-cols-3 gap-4 mt-10">
    <% @users.each do |user| %>
      <div class="bg-white shadow rounded border border-transparent hover:border-blue-500 cursor-pointer">
        <div class="h-48 w-full checker-bg flex items-center justify-center p-4 text-blue-500">
          <div class="w-36 h-36 bg-gray-100 rounded-full bg-cover bg-center">
            <% if user.avatar.attached? %>
              <%= image_tag user.avatar, class: 'avatar rounded-full' %>
            <% else %>
              <p>No avatar available</p>
            <% end %>
          </div>
        </div>

        <div class="p-4 border-t border-gray-200">
          <div class="flex items-center justify-between">
            
            <%= link_to other_user_path(user.nickname) do %>
              <h2 class="text-gray-600 font-medium">
                <%= user.nickname %>
              </h2>
            <% end %>

            <% if current_user.following.include?(user) %>
              <%= button_to 'Unfollow', subscription_path(current_user.active_subscriptions.find_by(followed_id: user.id)),
                method: :delete,
                class: "text-white bg-gradient-to-br from-green-400 to-blue-600 hover:bg-gradient-to-bl focus:ring-4 focus:outline-none focus:ring-green-200 dark:focus:ring-green-800 font-medium rounded-lg text-sm px-5 py-2.5 text-center me-2 mb-2" 
              %>
            <% else %>
              <%= button_to 'Follow', subscriptions_path(followed_id: user.id),
                class: "text-white bg-gradient-to-br from-pink-500 to-orange-400 hover:bg-gradient-to-bl focus:ring-4 focus:outline-none focus:ring-pink-200 dark:focus:ring-pink-800 font-medium rounded-lg text-sm px-5 py-2.5 text-center me-2 mb-2"
              %>
            <% end %>

          </div>
          <p class="text-gray-400 text-sm my-1">Active</p>
        </div>
      </div>
    <% end %>
  </div>

</section>

app/views/users/show.html.erb
<main class="profile-page bg-slate-200">
  <section class="relative py-16 bg-blueGray-200 mt-24">
    <div class="container mx-auto px-4">
      <div class="relative flex flex-col min-w-0 break-words bg-white w-full mb-6 shadow-xl rounded-lg">
        <div class="px-6">
          <div class="flex flex-wrap justify-center">
            <div class="w-full lg:w-3/12 px-4 lg:order-2 flex justify-center">
              <div class="relative w-40 h-40">
                <% if @user.avatar.attached? %>
                  <%= image_tag @user.avatar, class: 'shadow-xl rounded-full h-full w-full align-middle border-none' %> <!-- Обновлены стили -->
                <% else %>
                  <p>No avatar available</p>
                <% end %>
              </div>
            </div>
            <div class="w-full lg:w-4/12 px-4 lg:order-3 lg:text-right lg:self-center">
              <div class="py-6 px-3 mt-32 sm:mt-0">
                <div>
                  <p class="text-xl font-bold"><%= @user.name %> <%= @user.lastname %></p>
                  <p class="text-lg text-gray-600">Age: <%= @user.age %></p>
                </div>
                <% if not(@user == current_user) %>
                  <button class="bg-pink-500 active:bg-pink-600 uppercase text-white font-bold hover:shadow-md shadow text-xs px-4 py-2 rounded outline-none focus:outline-none sm:mr-2 mb-1 ease-linear transition-all duration-150" type="button">
                    Connect
                  </button>
                <% end %>
              </div>
            </div>
            <div class="w-full lg:w-4/12 px-4 lg:order-1">
              <div class="flex justify-center py-4 lg:pt-4 pt-8">
                <div class="mr-4 p-3 text-center">
                  <span class="text-xl font-bold block uppercase tracking-wide text-blueGray-600">
                    <%= @following_count %>
                  </span>
                  <span class="text-sm text-blueGray-400">
                    Following
                  </span>
                </div>
                <div class="mr-4 p-3 text-center">
                  <span class="text-xl font-bold block uppercase tracking-wide text-blueGray-600">
                    <%= @followers_count %>
                  </span>
                  <span class="text-sm text-blueGray-400">
                    Followers
                  </span>
                </div>
                <div class="lg:mr-4 p-3 text-center">
                  <span class="text-xl font-bold block uppercase tracking-wide text-blueGray-600">
                    <%= @posts.count %>
                  </span>
                  <span class="text-sm text-blueGray-400">
                    Posts
                  </span>
                </div>
              </div>
            </div>
          </div>
          <div class="text-center mt-12">
            <h3 class="text-4xl font-semibold leading-normal mb-2 text-blueGray-700 mb-2">
              <%= @user.nickname %>
            </h3>
          </div>
        </div>
      </div>
    </div>
  </section>


  <!-- Блок для вывода постов пользователя -->
  <section class="py-8">
    <div class="container mx-auto px-4">

      <div class="flex justify-center mb-8">
        <%= link_to "New Post", post_new_path(current_user.nickname), class: "bg-pink-500 hover:bg-pink-600 text-white font-bold py-2 px-4 rounded transition ease-in-out duration-150" %>
      </div>

      <div class="flex flex-wrap justify-center">
        <% @posts.each do |post| %>
          <div class="w-full md:w-1/2 lg:w-1/3 xl:w-1/4 px-4 mb-8">
            <div class="bg-white shadow-lg rounded-lg p-4">
              <%= link_to show_post_path(post.id), class: "text-xl font-semibold text-gray-800 mb-2" do %>
                <%= post.title %>
              <% end %>
              <p class="text-sm text-gray-600"><%= post.description %></p>

              <% if post.image.attached? %>
                <%= image_tag post.image, class: "mt-4 rounded-lg" %>
              <% end %>

              <div class="flex justify-between items-center mt-4">
                <%= render 'likes/like', post: post %>

                <span><%= post.comments.count %> Comments</span>

                <% if post.user_id == current_user.id %>
                  <div class="flex space-x-4">
                    <%= link_to "Edit", post_edit_path(current_user.nickname, post.id),
                      class: "text-blue-500"
                    %>
                    <%= link_to "Delete", delete_post_path(current_user.nickname, post.id), data: { turbo_method: :delete, turbo_confirm: "Are you sure?" } %>
                  </div>
                <% end %>
              </div>
            </div>
          </div>
        <% end %>
      </div>
    </div>
  </section>
</main>