config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  get "up" => "rails/health#show", as: :rails_health_check

  get "users/", to: "users#other_users", as: "users"
  get "users/:nickname", to: "users#other_user", as: "other_user"
  get ":nickname", to: "users#show", as: "profile"
  get ":nickname/edit", to: "users#edit", as: "edit_profile"
  patch ":nickname", to: "users#update", as: "update_profile"

  get ":nickname/posts/new", to: "posts#new", as: "post_new"
  get ":nickname/posts/:id/edit", to: "posts#edit", as: "post_edit"
  post ":nickname/posts", to: "posts#create", as: :create_post
  patch ":nickname/posts/:id", to: "posts#update", as: "update_post"
  put ":nickname/posts/:id", to: "posts#update"
  delete ":nickname/posts/:id", to: "posts#destroy", as: "delete_post"
  get ":nickname/posts", to: "posts#index", as: "posts"

  resources :users, only: [:show] do
    member do
      get :followers, :following
    end
  end

  resources :subscriptions, only: [:create, :destroy]

  resources :posts, only: [] do
    member do
      post 'like', to: 'likes#create'
      delete 'like', to: 'likes#destroy'
      get 'show', to: 'posts#show', as: :show
    end
    resources :comments, only: [:create, :destroy]
  end

  root "home#index"
end

app/models/post.rb
class Post < ApplicationRecord
  validates :title, presence: true, length: { minimum: 2 }

  belongs_to :user

  has_one_attached :image

  has_many :likes, dependent: :destroy
  has_many :liked_by_users, through: :likes, source: :user

  has_many :comments, dependent: :destroy

  def liked_by?(user)
    likes.exists?(user: user)
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: [:edit, :update, :destroy, :show]

  def destroy
    if params[:nickname] == current_user.nickname
      if @post.user_id == current_user.id
        @post.destroy
        redirect_to profile_path(current_user.nickname), alert: "Post deleted successfully"
      else
        redirect_to profile_path(current_user.nickname)
      end
    else
      redirect_to profile_path(current_user.nickname), alert: "User not found"
    end
  end

  def edit
    current_nickname = params[:nickname]
    if current_nickname == current_user.nickname
      # @post уже установлен в before_action
    else
      redirect_to profile_path(current_user.nickname), alert: "User not found"
    end
  end

  def index
    current_nickname = params[:nickname]
    if current_nickname == current_user.nickname
      subscribed_users_ids = current_user.following.pluck(:id)
      @posts = Post.where(user_id: subscribed_users_ids)
    else
      redirect_to profile_path(current_user.nickname), alert: "User not found"
    end
  end

  def new
    current_nickname = params[:nickname]
    if current_nickname == current_user.nickname
      @post = Post.new
    else
      redirect_to profile_path(current_user.nickname), alert: "User not found"
    end
  end

  def create
    @post = current_user.posts.build(post_params)
    if @post.save
      redirect_to profile_path(current_user.nickname), notice: "Post created successfully"
    else
      render :new
    end
  end

  def update
    current_nickname = params[:nickname]
    if current_nickname == current_user.nickname
      if @post.update(post_params)
        redirect_to profile_path(current_user.nickname), notice: "Post updated successfully"
      else
        render :edit
      end
    else
      redirect_to profile_path(current_user.nickname), alert: "User no"
    end
  end

  def show
    # @post уже установлен в before_action
  end

  private

  def post_params
    params.require(:post).permit(:title, :description, :image)
  end

  def set_post
    @post = Post.find(params[:id])
  end
end

app/views/posts/create.js.erb
<% if @comment.persisted? %>
  $("#comments").append("<%= j render @comment %>");
  $("#new_comment")[0].reset();
<% else %>
  alert("Comment could not be created");
<% end %>

app/views/posts/destroy.html.erb
$("#comment-<%= @comment.id %>").remove();

app/views/posts/edit.html.erb
<section class="pt-70 w-full h-screen bg-slate-200">
  <h1 class="text-6xl mt-6 mx-auto max-w-sm">Edit post</h1>

  <%= form_with model: @post, url: update_post_path(params[:nickname], @post), method: :patch, html: { class: "max-w-sm mx-auto" } do |f| %>
    <div class="field mb-5 mt-7">
			<%= f.label :title, class: "block mb-2 text-sm font-medium text-gray-900 dark:text-white" %>
			<%= f.text_field :title, presence: true, minlength: 2, placeholder: "Title", class: "bg-gray-50 border border-gray-300 text-gray-900 text-sm rounded-lg focus:ring-blue-500 focus:border-blue-500 block w-full p-2.5 dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400 dark:text-white dark:focus:ring-blue-500 dark:focus:border-blue-500" %>
		</div>

		<div class="field mb-5">
			<%= f.label :description, class: "block mb-2 text-sm font-medium text-gray-900 dark:text-white" %>
			<%= f.text_field :description, presence: true, placeholder: "Description", class: "bg-gray-50 border border-gray-300 text-gray-900 text-sm rounded-lg focus:ring-blue-500 focus:border-blue-500 block w-full p-2.5 dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400 dark:text-white dark:focus:ring-blue-500 dark:focus:border-blue-500" %>
		</div>

		<div class="field mb-5">
			<%= f.label "Upload file", class: "block mb-2 text-sm font-medium text-gray-900 dark:text-white" %>
			<%= f.file_field :image, class: "block w-full text-sm text-gray-900 border border-gray-300 rounded-lg cursor-pointer bg-gray-50 dark:text-gray-400 focus:outline-none dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400" %>
	  </div>

    <%= f.submit "Update post!", class: "w-full text-gray-500 font-medium text-base bg-gray-100 file:cursor-pointer cursor-pointer file:border-0 file:py-2.5 file:px-4 file:mr-4 file:bg-gray-800 file:hover:bg-gray-700 file:text-white rounded" %>
  <% end %>
</section>

app/views/posts/index.html.erb
<main class="pt-70 bg-slate-200 min-h-screen">
  <div class="w-[1000px] mx-auto">
    <h1 class="text-5xl mt-6">All Posts</h1>
  </div>

  <section class="py-8 mt-5">
    <div class="container mx-auto px-4">
      <div class="flex flex-wrap justify-center">
        <% @posts.each do |post| %>
          <div class="w-full md:w-1/2 lg:w-1/3 xl:w-1/4 px-4 mb-8">
            <span class="text-sm font-semibold text-gray-800 ml-4">Author: </span>

            <%= link_to other_user_path(post.user.nickname), class: "text-sm text-gray-600 mb-5 hover:text-red-500" do %>
              <%= post.user.nickname %>
            <% end %>

            <div class="bg-white shadow-lg rounded-lg p-4">

              <%= link_to show_post_path(post.id), class: "text-xl font-semibold text-gray-800 mb-2" do %>
                <%= post.title %>
              <% end %>

              <p class="text-sm text-gray-600"><%= post.description %></p>

              <% if post.image.attached? %>
                <%= image_tag post.image, class: "mt-4 rounded-lg" %>
              <% end %>

              <div class="flex justify-between items-center mt-4">
                <%= render 'likes/like', post: post %>

                <span><%= post.comments.count %> Comments</span>

                <% if post.user_id == current_user.id %>
                  <div class="flex space-x-4">
                    <%= link_to "Edit", post_edit_path(current_user.nickname, post.id),
                      class: "text-blue-500"
                    %>
                    <%= link_to "Delete", delete_post_path(current_user.nickname, post.id), data: { turbo_method: :delete, turbo_confirm: "Are you sure?" } %>
                  </div>
                <% end %>
              </div>
            </div>
          </div>
        <% end %>
      </div>
    </div>
  </section>
</main>

app/views/posts/new.html.erb
<section class="pt-70 w-full h-screen bg-slate-200">	
	<h1 class="text-6xl	mt-6 mx-auto max-w-sm">New post</h1>

	<%= form_with model: @post, html: { class: "max-w-sm mx-auto" } do |f| %>
		<div class="field mb-5 mt-7">
			<%= f.label :title, class: "block mb-2 text-sm font-medium text-gray-900 dark:text-white" %>
			<%= f.text_field :title, presence: true, minlength: 2, placeholder: "Title", class: "bg-gray-50 border border-gray-300 text-gray-900 text-sm rounded-lg focus:ring-blue-500 focus:border-blue-500 block w-full p-2.5 dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400 dark:text-white dark:focus:ring-blue-500 dark:focus:border-blue-500" %>
		</div>

		<div class="field mb-5">
			<%= f.label :description, class: "block mb-2 text-sm font-medium text-gray-900 dark:text-white" %>
			<%= f.text_field :description, presence: true, placeholder: "Description", class: "bg-gray-50 border border-gray-300 text-gray-900 text-sm rounded-lg focus:ring-blue-500 focus:border-blue-500 block w-full p-2.5 dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400 dark:text-white dark:focus:ring-blue-500 dark:focus:border-blue-500" %>
		</div>

		<div class="field mb-5">
			<%= f.label "Upload file", class: "block mb-2 text-sm font-medium text-gray-900 dark:text-white" %>
			<%= f.file_field :image, class: "block w-full text-sm text-gray-900 border border-gray-300 rounded-lg cursor-pointer bg-gray-50 dark:text-gray-400 focus:outline-none dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400" %>
	  </div>

		<%= f.submit "Submit post!", class: "w-full text-gray-500 font-medium text-base bg-gray-100 file:cursor-pointer cursor-pointer file:border-0 file:py-2.5 file:px-4 file:mr-4 file:bg-gray-800 file:hover:bg-gray-700 file:text-white rounded" %>
	<% end %>
</section>

app/views/posts/show.html.erb
<main class="pt-70 bg-slate-200 min-h-screen py-8">
  <div class="container mx-auto px-4">
    <div class="bg-white shadow-lg rounded-lg p-8 max-w-full">
      <h1 class="text-4xl font-bold text-gray-800 mb-4"><%= @post.title %></h1>
      <p class="text-lg text-gray-700 mb-4"><%= @post.description %></p>

      <% if @post.user_id == current_user.id %>
        <div class="flex space-x-4">
          <%= link_to "Edit", post_edit_path(current_user.nickname, @post.id),
            class: "text-blue-500"
          %>
          <%= link_to "Delete", delete_post_path(current_user.nickname, @post.id), data: { turbo_method: :delete, turbo_confirm: "Are you sure?" } %>
        </div>
      <% end %>

      <% if @post.image.attached? %>
        <div class="flex justify-center mb-4">
          <%= image_tag @post.image, class: "rounded-lg max-w-full mt-5" %>
        </div>
      <% end %>

      <p class="text-sm text-gray-500 mb-6">Posted on: <%= @post.created_at.strftime("%B %d, %Y") %></p>

      <!-- Like Button -->
      <div class="flex items-center mb-6">
        <%= render 'likes/like', post: @post %>
      </div>

      <h2 class="text-2xl font-semibold text-gray-800 mb-4">Comments</h2>
      <div id="comments" class="space-y-4">
        <%= render @post.comments %>
      </div>

      <div class="mt-8">
        <%= render 'comments/form' %>
      </div>
    </div>
  </div>
</main>