config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  get "up" => "rails/health#show", as: :rails_health_check

  get "users/", to: "users#other_users", as: "users"
  get "users/:nickname", to: "users#other_user", as: "other_user"
  get ":nickname", to: "users#show", as: "profile"
  get ":nickname/edit", to: "users#edit", as: "edit_profile"
  patch ":nickname", to: "users#update", as: "update_profile"

  get ":nickname/posts/new", to: "posts#new", as: "post_new"
  get ":nickname/posts/:id/edit", to: "posts#edit", as: "post_edit"
  post ":nickname/posts", to: "posts#create", as: :create_post
  patch ":nickname/posts/:id", to: "posts#update", as: "update_post"
  put ":nickname/posts/:id", to: "posts#update"
  delete ":nickname/posts/:id", to: "posts#destroy", as: "delete_post"
  get ":nickname/posts", to: "posts#index", as: "posts"

  resources :users, only: [:show] do
    member do
      get :followers, :following
    end
  end

  resources :subscriptions, only: [:create, :destroy]

  resources :posts, only: [] do
    member do
      post 'like', to: 'likes#create'
      delete 'like', to: 'likes#destroy'
      get 'show', to: 'posts#show', as: :show
    end
    resources :comments, only: [:create, :destroy]
  end

  root "home#index"
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>PhotoFlow</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "tailwind", "inter-font", "data-turbo-track": "reload" %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <nav class="bg-white dark:bg-gray-900 fixed w-full z-20 top-0 start-0 border-b border-gray-200 dark:border-gray-600">
      <div class="max-w-screen-xl flex flex-wrap items-center justify-between mx-auto p-4">
        <%= link_to root_path, class: "inline-block flex items-center text-2xl text-white ml-32" do %>
          <img src="https://flowbite.com/docs/images/logo.svg" class="h-8" alt="Flowbite Logo">
          <span class="self-center text-2xl font-semibold whitespace-nowrap text-black">PhotoFlow</span>
        <% end %>
        
        <% if user_signed_in? %>
          <div class="flex md:order-2 space-x-3 md:space-x-0 rtl:space-x-reverse">
            <%= link_to "Sing out", destroy_user_session_path, data: { turbo_method: :delete }, class: "text-white bg-blue-700 hover:bg-blue-800 focus:ring-4 focus:outline-none focus:ring-blue-300 font-medium rounded-lg text-sm px-4 py-2 text-center dark:bg-blue-600 dark:hover:bg-blue-700 dark:focus:ring-blue-800" %>
            <button data-collapse-toggle="navbar-sticky" type="button" class="inline-flex items-center p-2 w-10 h-10 justify-center text-sm text-gray-500 rounded-lg md:hidden hover:bg-gray-100 focus:outline-none focus:ring-2 focus:ring-gray-200 dark:text-gray-400 dark:hover:bg-gray-700 dark:focus:ring-gray-600" aria-controls="navbar-sticky" aria-expanded="false">
              <span class="sr-only">Open main menu</span>
              <svg class="w-5 h-5" aria-hidden="true" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 17 14">
                <path stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M1 1h15M1 7h15M1 13h15"/>
              </svg>
            </button>
          </div>
        <% end %>

        <div class="items-center justify-between hidden w-full md:flex md:w-auto md:order-1" id="navbar-sticky">
          <ul class="flex flex-col p-4 md:p-0 mt-4 font-medium border border-gray-100 rounded-lg bg-gray-50 md:space-x-8 rtl:space-x-reverse md:flex-row md:mt-0 md:border-0 md:bg-white dark:bg-gray-800 md:dark:bg-gray-900 dark:border-gray-700">
            <% if user_signed_in? %>
              <li>
                <%= link_to "Your Profile", profile_path(:nickname), class: "lock py-2 px-3 text-white bg-blue-700 rounded md:bg-transparent md:text-blue-700 md:p-0 md:dark:text-blue-500" %>
              </li>

              <li>
                <%= link_to "Settings", edit_profile_path(current_user.nickname), class: "block py-2 px-3 text-gray-900 rounded hover:bg-gray-100 md:hover:bg-transparent md:hover:text-blue-700 md:p-0 md:dark:hover:text-blue-500 dark:text-white dark:hover:bg-gray-700 dark:hover:text-white md:dark:hover:bg-transparent dark:border-gray-700" %> 
              </li>

              <li>
                <%= link_to "Users", users_path, class: "block py-2 px-3 text-gray-900 rounded hover:bg-gray-100 md:hover:bg-transparent md:hover:text-blue-700 md:p-0 md:dark:hover:text-blue-500 dark:text-white dark:hover:bg-gray-700 dark:hover:text-white md:dark:hover:bg-transparent dark:border-gray-700" %> 
              </li>

              <li>
                <%= link_to "Posts", posts_path(current_user.nickname), class: "block py-2 px-3 text-gray-900 rounded hover:bg-gray-100 md:hover:bg-transparent md:hover:text-blue-700 md:p-0 md:dark:hover:text-blue-500 dark:text-white dark:hover:bg-gray-700 dark:hover:text-white md:dark:hover:bg-transparent dark:border-gray-700" %> 
              </li>
            <% else %>
              <li>
                <%= link_to "Log in", new_user_session_path, class: "lock py-2 px-3 text-white bg-blue-700 rounded md:bg-transparent md:text-blue-700 md:p-0 md:dark:text-blue-500" %>
              </li>
            <% end %>
          </ul>
        </div>
      
      </div>
    </nav>

    <p class="notice"><%= notice %></p> 
    <p class="alert"><%= alert %></p> 
    <%= yield %>
  </body>
</html>